Add controllers
ImING0/java-shareit pull request #2
Opened 2023-10-19 18:06 UTC by ImING0

2023-10-19 19:54 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private final Long id; // ID of the booking
Это все не используемые заготовки, но тем не менее:
- id у dto не будет
- комментарии вот такого плана не нужны, названия переменных хватает

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ResponseEntity<ItemDto> updateItem(@RequestHeader(requestHeader) Long userId,
- Параметры хочется видеть рядом, вот так "причесать" например

```
    public ResponseEntity<ItemDto> updateItem(@RequestHeader(requestHeader) Long userId,
                                              @PathVariable Long itemId,
                                              @RequestBody Item item) {
```

- Принимать нужно `ItemDto`, а не `Item`
- Валидация нужна не только при создании

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/controller/ItemControllerExceptionHandler.java
> +    @ExceptionHandler(value = {UserNotFoundException.class})
Мы не создаём классы исключений под каждую сущность...
Создаётся один общий класс исключений.
Бросая его, ты в сообщении будешь писать, что именно произошло.

Ты замучаешься создавать классы под каждую сущность отдельно, в большом проекте.
Класс ExceptionHandler так же должен быть один.

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotBlank(message = "The name cannot be empty")
Валидация должна быть у `dto`. 
Эта сущность это модель для персистентности, тут будут другие аннотации, но не в этой итерации.

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/IUserService.java
> +    UserDto createUser(User user);
Из названия методов желательно убрать название сущности: `user`.
С чем мы работаем понятно из названия класса.

`createUser -> create`, `getUserById -> getById`

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/IItemStorage.java
> +    Optional<Item> save(Long userId, Item item);
`Optional` уместен только для метода `getItemById`.
При создании или обновлении мы или выполним операцию успешно и можно вернуть саму сущность `Item`, или упадем с ошибкой, но она будет перехвачена и обработана.
Поэтому тут нет неопределенности и не нужно `Optional`

И второе, давай в сервисах использовать глагол `get`, а тут `find`.

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/impl/ItemStorageInMemory.java
> +        throwIfItemNotFound(itemId);
Ты прописал логику в хранилище и это не правильно!
Все проверки должны были бы быть в сервисе.

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/impl/ItemStorageInMemory.java
> +        return Optional.of(items.get(itemId));
Вот, например, throwIfItemNotFound(itemId) - должно быть в сервисе.
Тут только `return Optional.of(items.get(itemId));`

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/impl/UserService.java
> +        userStorage.save(user);
Вот сервисы у тебя и пустые и ничего и не делают. Потому что все в хранилище.
Логику реализуем тут... проверяем, например, есть ли такая запись - если есть кидаем исключение.

2023-10-19 19:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/impl/UserService.java
> +                .orElse(null);
Не возвращай `null` - это плохая практика!
Тем более что бы позаботился и возвращаешь Optional - теперь осталось им только воспользоваться.

После того как ты сходил в хранилище за объектом ты должен понять вернули его или Optional пуст. Если пусть то кидаешь исключение, если нет - возвращаешь.

2023-10-19 19:54 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +    @Test
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`
2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём.
Потом по степени "тяжеловестности" остальные зависимости. Ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2023-10-19 19:54 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +    }
### application.properties

И про файл настроек `application.properties`, так как он не менялся, тоже тут напишу...

Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели ))

Соответственно - попрошу тебя этому следовать.

2023-10-20 13:10 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private final Long id; // ID of the booking
Убрал поле id пока только у request и booking, когда убираю у user и item сыпятся тесты постман, так как он ожидает поле id ,  без него увы тесты не идут. Либо оставлять у DTO user , item поле ID, либо возвращать не DTO, а User, Item классы

2023-10-20 13:20 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ResponseEntity<ItemDto> updateItem(@RequestHeader(requestHeader) Long userId,
Хорошо, на вход сделаю также DTO , но вот валидацию на update увы сделать не получится. При обновлении на вход может прийти DTO, у которого нет всех полей, например только описание, валидация его просто не пропустит дальше. Поэтому проверка организована уже дальше внутри кода,  чтобы все таки обновить объект.

2023-10-20 16:35 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/controller/ItemControllerExceptionHandler.java
> +    @ExceptionHandler(value = {UserNotFoundException.class})
Согл, сделаю, просто по ТЗ понял что в каждом пакете свое.

2023-10-20 17:19 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotBlank(message = "The name cannot be empty")
Правильно понял, что у классов User и тп не должно быть валидации? Почему если так?

В любом случае уберу, ведь на вход теперь и так поступает ДТО.

2023-10-20 17:28 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/user/service/IUserService.java
> +    UserDto createUser(User user);
Исправлено

2023-10-20 18:08 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/storage/IItemStorage.java
> +    Optional<Item> save(Long userId, Item item);
Про опшинал понял, сделаю

А вот почему в сервисе гет а  в хранилище файнд? сделаю, просто для понимания мне)

2023-10-20 19:02 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/storage/impl/ItemStorageInMemory.java
> +        throwIfItemNotFound(itemId);
Я сделаю в сервисе, но хотел бы понять почему именно так? Просто мне кажется такие проверки логичнее делать в хранилище и там же кидать исключения. Как оно на практике?
throwIfEmailDuplicate оставил в храниоище, согласен с этим? ПОтому что для его реализации нужен второй метод получения юзера по emai.  Все равно на БД перейдем)

Также приходится в сервис внедрять хранилище, это норм? Или  я что то не так сделал.

2023-10-20 19:03 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/storage/impl/ItemStorageInMemory.java
> +        return Optional.of(items.get(itemId));
сделал.

2023-10-20 19:19 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/user/service/impl/UserService.java
> +        userStorage.save(user);
перенес)

2023-10-20 19:22 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/user/service/impl/UserService.java
> +                .orElse(null);
исправил

2023-10-20 19:34 UTC, ImING0 commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +    @Test
когда зашел  в pom файл инфаркт чуть не хватил, много там всего однако, хах) добавил .

2023-10-20 20:03 UTC, ImING0 commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +    }
сделал

2023-10-20 23:17 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotBlank(message = "The name cannot be empty")
Ну частично я попытался сразу пояснить. 
Ну а так просто потому что валидируем мы dto, которая потом мапится в персистентную сущность(entity) `UserDto -> User`. Зачем нам одинаковые проверки в двух местах.

2023-10-20 23:20 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/IItemStorage.java
> +    Optional<Item> save(Long userId, Item item);
Для порядку! ))
Нет никакой такой магии в этом, просто "я художник - я так вижу".

Сейчас ты подключишь фреймворки и библиотеки и увидишь что там в репозитории `find` будешь воспринимать его как родного!  ))

2023-10-20 23:21 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotBlank(message = "The name cannot be empty")
ага, тупой вопрос задал))

2023-10-20 23:23 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/storage/impl/ItemStorageInMemory.java
> +        throwIfItemNotFound(itemId);
throwIfEmailDuplicate  я вроде таки убрал оттуда, добавил доп метод просто

2023-10-20 23:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/impl/ItemStorageInMemory.java
> +        throwIfItemNotFound(itemId);
"хотел бы понять почему именно так?" - разделение ответственности.
Хранилище ответственно только за работу с базой(ну или где там у нас хранится все).

"throwIfEmailDuplicate оставил в храниоище, согласен с этим?" - нет, это не верно. 
Это относится к логике работы нашего приложения, а что если мы не хотим запрещать дубли?

Да, все верно, использовать в сервисе хранилища - это то что нужно.
В трёх уровненной архитектуре, контроллеры взаимодействуют с сервисами, а сервисы с хранилищами.

2023-10-20 23:40 UTC, FanaticFiz approved these changes

2023-10-20 23:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/IllegalNameOrDescriptionException.java
> +public class IllegalNameOrDescriptionException extends RuntimeException {
Вот тут ты всё еще конкретно про два параметра говоришь.
Получается не сможешь этот класс использовать, когда проблемы будут в других местах?

Называй классы исключений в соответствии с `HTTP` статус кодами которые они будут порождать!
Этот класс стоило бы назвать соответствующе: `BadRequestException`

2023-10-20 23:42 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/exception/IllegalNameOrDescriptionException.java
> +public class IllegalNameOrDescriptionException extends RuntimeException {
поправлю)

2023-10-20 23:49 UTC, merged