add-bookings
ImING0/java-shareit pull request #3
Opened 2023-10-26 12:59 UTC by ImING0

2023-10-26 19:04 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(name = "state", defaultValue = "ALL") String state) {
Принимай параметр сразу как тип `State`.

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            throw new BadRequestException(String.format("Unknown state: %s", state));
Не понимаю назначения этого `try/catch`.
Такое исключение выkетает из-за `State.valueOf(state)` ? 

Такая надобность или отпадет или сделай это в отдельном методе

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Long id;
При обилии аннотаций всё сливается - делай отступы между полями.

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Enumerated(EnumType.STRING)
И что простое `private Status status = Status.WAITING;` не работает?
Ну выкинь ломбок, напиши все ручками - управляй классом самостоятельно.

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    /*Покажет, брал ли пользователь эту вещь в аренду и завершилась ли она*/
Оформляй комменты как `javaDoc`
Дело в том что он будет доступен при просмотре метода, это комбинация клавиш `ctrl+q`
Ну и в случае автогенерации документации и прочее...
Вот так это выглядит.

![image](https://github.com/ImING0/java-shareit/assets/3994663/e64fa605-e36b-45d9-ad9b-9e44b09aeb43)

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/IBookingService.java
> +    BookingDtoOut getByBookingIdAndUserId(Long bookingId,
Мне не нравятся названия трех последних методов.
Не вижу сути...
Ну названия собраны как у репозитория, но тут же не он, тут можно написать понятно.

А между `getAllBookingsForCurrentUserId` и `getAllItemBookingsForOwnerId` вообще разницы не улавливаю... принимают одинаковые параметры и возвращают одинаковый список!

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingService.java
> +    private final UserMapper userMapper;
мапперы не используются...

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingService.java
> +        booking.setStatus(Status.WAITING);
В мапере вижу установку статуса в WAITING тут лишнее получается...

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .id(item.getId())
Ну ваще не красиво!! :face_with_spiral_eyes: 

Код, повторяется 4-е раза, ну можно же с этим что-то сделать!

```
                .id(item.getId())
                .owner(item.getOwner())
                .name(item.getName())
                .description(item.getDescription())
                .available(item.getAvailable())
```

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("select i " + "from Item as i " + "where i.available = true and "
Оформляй запросы, набирая команды SQL в верхнем регистре: SELECT

2023-10-26 19:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    // Мне кажется, что проверки на нулль тут избыточны, ведь в БД уже есть проверка на это?
Это как бы не проверка, а контракт.
Ты подсказываешь как генерить эти колонки в БД, в случае если оно происходит автоматом.
Ты подсказываешь разработчикам как оно должно быть создано в БД.

2023-10-29 19:10 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Enumerated(EnumType.STRING)
Ок

2023-10-29 19:52 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    /*Покажет, брал ли пользователь эту вещь в аренду и завершилась ли она*/
Классное решение, добавил в репозитории)

2023-10-29 20:17 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/service/IBookingService.java
> +    BookingDtoOut getByBookingIdAndUserId(Long bookingId,
Последние два метода, getAllBookingsForCurrentUserId и getAllItemBookingsForOwnerId, действительно принимают одинаковые параметры и возвращают похожие списки. Это связано с тем, что оба метода служат для получения списка бронирований, но они предназначены для разных видов пользователей: getAllBookingsForCurrentUserId - для текущего пользователя, а getAllItemBookingsForOwnerId - для владельца. Названия методов отражают эту разницу и обеспечивают ясность в том, какой тип бронирований ожидается при вызове каждого из них.

Однако, я готов улучшить читаемость кода, добавив поясняющие JavaDocs к этим методам. Это поможет разработчикам легче понимать, какие данные они могут ожидать в ответе. Если у вас есть предложения по изменению названий методов, я готов их рассмотреть.

2023-10-29 20:21 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingService.java
> +    private final UserMapper userMapper;
удалил, видимо использовались да перестали во время разработки)

2023-10-29 20:28 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/service/IBookingService.java
> +    BookingDtoOut getByBookingIdAndUserId(Long bookingId,
getByBookingIdAndUserId изменил на getBookingById

2023-10-29 21:27 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingService.java
> +        booking.setStatus(Status.WAITING);
Ну да, логичнее перенести это вообще в слой сервиса.

2023-10-29 21:36 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("select i " + "from Item as i " + "where i.available = true and "
Сделал

2023-10-29 22:19 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .id(item.getId())
Согласен, убожество еще то! Аж самому блевать захотелось, когда перечитал)

2023-10-29 22:20 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .id(item.getId())
поменять в общем логику. мапперы в топку, в сервисе теперь всё как надо

2023-10-29 22:21 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Long id;
Это можно поставить как условие в код стайле? Не нашел такой опции, пока оставлю так.

2023-10-29 22:36 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(name = "state", defaultValue = "ALL") String state) {
Решил иначе, ниже подробности

2023-10-29 22:38 UTC, ImING0 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            throw new BadRequestException(String.format("Unknown state: %s", state));
Сделал отедбныей метод. Тесты требуют особенной обработки этой ошибки. Сделал статик метод для преобразования из строки в State, он выкинет то, что просит постман тест. Что то еще городить не вижу смысла

2023-10-30 18:51 UTC, FanaticFiz approved these changes

2023-10-30 19:56 UTC, merged